// Generates src/proto_descriptor.ts — the omle.proto schema as a protobufjs
// JSON descriptor, so fromProtoBinary() can decode .omle files without
// shipping the 100 kB .proto text or the .proto grammar parser.
//
// Like scripts/gen_ir_ts.py, the output is committed: the published package
// must carry the schema, so consumers never fetch anything at build time.
//
// Resolution order matches gen_ir_ts.py:
//   1. OMLE_PROTO_PATH env var — explicit local path (dev / pre-push)
//   2. git clone from GitHub   — default for CI and released state
//                                Ref: OMLE_PROTO_REF env var, default "main"
//
// Usage: node scripts/gen_proto_descriptor.mjs src/proto_descriptor.ts

import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import protobuf from 'protobufjs';

const PROTO_REPO = 'openmle/omle';
const PROTO_PATH = 'protobuf/omle.proto';
const PROTO_REF = process.env.OMLE_PROTO_REF ?? 'main';

const outPath = process.argv[2];
if (!outPath) {
  console.error('Usage: node scripts/gen_proto_descriptor.mjs <out.ts>');
  process.exit(1);
}

function fail(message, tip) {
  console.error(`Error: ${message}`);
  if (tip) console.error(`  Tip: ${tip}`);
  process.exit(1);
}

function readProto() {
  const override = process.env.OMLE_PROTO_PATH;
  if (override) {
    const file = resolve(override);
    if (!existsSync(file)) fail(`OMLE_PROTO_PATH=${override} does not exist.`);
    console.error(`Using local proto: ${file}`);
    return readFileSync(file, 'utf8');
  }

  const token = process.env.GITHUB_TOKEN;
  const remote = token
    ? `https://x-access-token:${token}@github.com/${PROTO_REPO}.git`
    : `https://github.com/${PROTO_REPO}.git`;

  console.error(`Cloning ${PROTO_REPO}@${PROTO_REF} to get ${PROTO_PATH}`);
  const clone = mkdtempSync(join(tmpdir(), 'omle_proto_'));
  try {
    execFileSync('git', ['clone', '--depth=1', '--branch', PROTO_REF, remote, clone],
                 { stdio: ['ignore', 'ignore', 'pipe'] });
    const file = join(clone, PROTO_PATH);
    if (!existsSync(file)) fail(`${PROTO_PATH} not found in ${PROTO_REPO}@${PROTO_REF}.`);
    return readFileSync(file, 'utf8');
  } catch (e) {
    fail(`git clone failed: ${e.stderr?.toString().trim() ?? e.message}`,
         'set OMLE_PROTO_PATH=/path/to/omle.proto to use a local copy.');
  } finally {
    rmSync(clone, { recursive: true, force: true });
  }
}

// keepCase preserves snake_case field names, matching the JSON convention
// fromJSON() expects. Changing it would silently rename every field.
const root = protobuf.parse(readProto(), { keepCase: true }).root;
const descriptor = root.toJSON();

const banner = `// Generated by scripts/gen_proto_descriptor.mjs — DO NOT EDIT.
//
// The omle.proto schema as a protobufjs JSON descriptor. Regenerate with:
//   npm run gen:proto:local   (from a sibling omle checkout)
//   npm run gen:proto         (clones openmle/omle@main)

import type { INamespace } from 'protobufjs/light.js';

export const protoDescriptor = ${JSON.stringify(descriptor, null, 2)} as unknown as INamespace;

export default protoDescriptor;
`;

writeFileSync(outPath, banner);
console.error(`Wrote ${outPath} (${(banner.length / 1024).toFixed(1)} kB)`);
