// Generated by scripts/gen_proto_descriptor.mjs — DO NOT EDIT.
//
// The omle.proto schema as a protobufjs JSON descriptor. Regenerate with:
//   npm run gen:proto:local   (from a sibling omle checkout)
//   npm run gen:proto         (clones openmle/omle@main)

import type { INamespace } from 'protobufjs/light.js';

export const protoDescriptor = {
  "nested": {
    "omle": {
      "nested": {
        "OMLEModel": {
          "fields": {
            "metadata": {
              "type": "ModelMetadata",
              "id": 1
            },
            "operator_imports": {
              "rule": "repeated",
              "type": "NamespaceImport",
              "id": 2
            },
            "function_imports": {
              "rule": "repeated",
              "type": "NamespaceImport",
              "id": 3
            },
            "inputs": {
              "rule": "repeated",
              "type": "InputSpec",
              "id": 4
            },
            "outputs": {
              "rule": "repeated",
              "type": "OutputSpec",
              "id": 5
            },
            "model_schema": {
              "type": "ModelSchema",
              "id": 6
            },
            "nodes": {
              "rule": "repeated",
              "type": "Node",
              "id": 7
            },
            "verification": {
              "type": "ModelVerification",
              "id": 8
            },
            "warmup": {
              "type": "RuntimeWarmup",
              "id": 9
            },
            "sample_inputs": {
              "type": "SampleInputSet",
              "id": 10
            },
            "tensor_entries": {
              "rule": "repeated",
              "type": "TensorEntry",
              "id": 20
            },
            "functions": {
              "rule": "repeated",
              "type": "DefineFunction",
              "id": 30
            }
          }
        },
        "SourceFramework": {
          "fields": {
            "name": {
              "type": "string",
              "id": 1
            },
            "version": {
              "type": "string",
              "id": 2
            },
            "role": {
              "type": "string",
              "id": 3
            }
          }
        },
        "ModelMetadata": {
          "fields": {
            "format_version": {
              "type": "string",
              "id": 1
            },
            "name": {
              "type": "string",
              "id": 2
            },
            "version": {
              "type": "string",
              "id": 3
            },
            "timestamp": {
              "type": "string",
              "id": 4
            },
            "producer": {
              "type": "string",
              "id": 5
            },
            "producer_version": {
              "type": "string",
              "id": 6
            },
            "source_frameworks": {
              "rule": "repeated",
              "type": "SourceFramework",
              "id": 7
            },
            "doc_string": {
              "type": "string",
              "id": 8
            },
            "copyright": {
              "type": "string",
              "id": 9
            },
            "attributes": {
              "keyType": "string",
              "type": "string",
              "id": 20
            }
          }
        },
        "NamespaceImport": {
          "fields": {
            "namespace": {
              "type": "string",
              "id": 1
            },
            "version": {
              "type": "string",
              "id": 2
            }
          }
        },
        "DataType": {
          "values": {
            "DATA_TYPE_UNSPECIFIED": 0,
            "BOOL": 1,
            "INT8": 2,
            "INT16": 3,
            "INT32": 4,
            "INT64": 5,
            "UINT8": 6,
            "UINT16": 7,
            "UINT32": 8,
            "UINT64": 9,
            "FLOAT16": 10,
            "FLOAT32": 11,
            "FLOAT64": 12,
            "STRING": 13,
            "BYTES": 14,
            "DATE": 15,
            "TIME": 16,
            "TIMESTAMP": 17
          }
        },
        "MeasureLevel": {
          "values": {
            "MEASURE_LEVEL_UNSPECIFIED": 0,
            "CONTINUOUS": 1,
            "NOMINAL": 2,
            "ORDINAL": 3,
            "FLAG": 4
          }
        },
        "TaskType": {
          "values": {
            "TASK_TYPE_UNSPECIFIED": 0,
            "REGRESSION": 1,
            "BINARY": 2,
            "MULTICLASS": 3,
            "CLUSTERING": 4,
            "ANOMALY_DETECTION": 5
          }
        },
        "OutputRole": {
          "values": {
            "OUTPUT_ROLE_UNSPECIFIED": 0,
            "PREDICTION": 1,
            "PROBABILITY": 2,
            "SCORE": 3,
            "CONFIDENCE": 4,
            "STANDARD_ERROR": 5,
            "STANDARD_DEVIATION": 6,
            "RESIDUAL": 7,
            "TRANSFORMED_VALUE": 8,
            "ENTITY_ID": 9,
            "AFFINITY": 10,
            "CONTRIBUTION": 11,
            "INTERMEDIATE": 12
          }
        },
        "Scalar": {
          "oneofs": {
            "value": {
              "oneof": [
                "bool_value",
                "int_value",
                "float_value",
                "double_value",
                "string_value"
              ]
            }
          },
          "fields": {
            "bool_value": {
              "type": "bool",
              "id": 1
            },
            "int_value": {
              "type": "int64",
              "id": 2
            },
            "float_value": {
              "type": "float",
              "id": 3
            },
            "double_value": {
              "type": "double",
              "id": 4
            },
            "string_value": {
              "type": "string",
              "id": 5
            }
          }
        },
        "InputSpec": {
          "fields": {
            "name": {
              "type": "string",
              "id": 1
            },
            "type": {
              "type": "TensorType",
              "id": 2
            },
            "description": {
              "type": "string",
              "id": 3
            },
            "attributes": {
              "keyType": "string",
              "type": "string",
              "id": 20
            }
          }
        },
        "OutputSpec": {
          "fields": {
            "name": {
              "type": "string",
              "id": 1
            },
            "type": {
              "type": "TensorType",
              "id": 2
            },
            "role": {
              "type": "OutputRole",
              "id": 3
            },
            "binding": {
              "type": "OutputBinding",
              "id": 4
            },
            "description": {
              "type": "string",
              "id": 5
            },
            "field_names": {
              "rule": "repeated",
              "type": "string",
              "id": 6
            },
            "attributes": {
              "keyType": "string",
              "type": "string",
              "id": 20
            }
          }
        },
        "OutputBinding": {
          "fields": {
            "target_name": {
              "type": "string",
              "id": 1
            },
            "values": {
              "rule": "repeated",
              "type": "Scalar",
              "id": 2
            },
            "segment_id": {
              "type": "string",
              "id": 3
            },
            "rank": {
              "type": "int32",
              "id": 4
            },
            "attributes": {
              "keyType": "string",
              "type": "string",
              "id": 20
            }
          }
        },
        "ModelSchema": {
          "fields": {
            "features": {
              "rule": "repeated",
              "type": "Feature",
              "id": 1
            },
            "targets": {
              "rule": "repeated",
              "type": "Target",
              "id": 2
            }
          }
        },
        "NameRange": {
          "fields": {
            "prefix": {
              "type": "string",
              "id": 1
            },
            "start": {
              "type": "int32",
              "id": 2
            },
            "end": {
              "type": "int32",
              "id": 3
            },
            "width": {
              "type": "int32",
              "id": 4
            }
          }
        },
        "Feature": {
          "oneofs": {
            "naming": {
              "oneof": [
                "name",
                "range"
              ]
            }
          },
          "fields": {
            "name": {
              "type": "string",
              "id": 1
            },
            "range": {
              "type": "NameRange",
              "id": 2
            },
            "description": {
              "type": "string",
              "id": 3
            },
            "type": {
              "type": "TensorType",
              "id": 4
            },
            "measure_level": {
              "type": "MeasureLevel",
              "id": 5
            },
            "source": {
              "type": "string",
              "id": 6
            },
            "index": {
              "type": "int32",
              "id": 7
            },
            "missing_value_policy": {
              "type": "MissingValuePolicy",
              "id": 8
            },
            "missing_replacement_value": {
              "type": "Scalar",
              "id": 9
            },
            "invalid_value_policy": {
              "type": "InvalidValuePolicy",
              "id": 10
            },
            "invalid_replacement_value": {
              "type": "Scalar",
              "id": 11
            },
            "outlier_value_policy": {
              "type": "OutlierValuePolicy",
              "id": 12
            },
            "domain": {
              "type": "ValueDomain",
              "id": 13
            },
            "attributes": {
              "keyType": "string",
              "type": "string",
              "id": 20
            }
          },
          "nested": {
            "MissingValuePolicy": {
              "values": {
                "MISSING_PROPAGATE": 0,
                "MISSING_AS_VALUE": 1,
                "MISSING_AS_INVALID": 2
              }
            },
            "InvalidValuePolicy": {
              "values": {
                "INVALID_RETURN_INVALID": 0,
                "INVALID_AS_IS": 1,
                "INVALID_AS_MISSING": 2,
                "INVALID_AS_VALUE": 3
              }
            },
            "OutlierValuePolicy": {
              "values": {
                "OUTLIER_AS_IS": 0,
                "OUTLIER_AS_MISSING": 1,
                "OUTLIER_AS_EXTREME": 2
              }
            }
          }
        },
        "Target": {
          "fields": {
            "name": {
              "type": "string",
              "id": 1
            },
            "type": {
              "type": "TensorType",
              "id": 2
            },
            "kind": {
              "type": "TargetKind",
              "id": 3
            },
            "measure_level": {
              "type": "MeasureLevel",
              "id": 4
            },
            "class_labels": {
              "rule": "repeated",
              "type": "Scalar",
              "id": 5
            },
            "description": {
              "type": "string",
              "id": 6
            },
            "attributes": {
              "keyType": "string",
              "type": "string",
              "id": 20
            }
          },
          "nested": {
            "TargetKind": {
              "values": {
                "TARGET_KIND_UNSPECIFIED": 0,
                "REGRESSION": 1,
                "BINARY": 2,
                "MULTICLASS": 3
              }
            }
          }
        },
        "ValueDomain": {
          "fields": {
            "continuous": {
              "type": "ContinuousDomain",
              "id": 1
            },
            "discrete": {
              "type": "DiscreteDomain",
              "id": 2
            }
          }
        },
        "ContinuousDomain": {
          "fields": {
            "intervals": {
              "rule": "repeated",
              "type": "Interval",
              "id": 1
            }
          }
        },
        "Interval": {
          "fields": {
            "left_margin": {
              "type": "Scalar",
              "id": 1
            },
            "right_margin": {
              "type": "Scalar",
              "id": 2
            },
            "closure": {
              "type": "Closure",
              "id": 3
            }
          },
          "nested": {
            "Closure": {
              "values": {
                "CLOSURE_UNSPECIFIED": 0,
                "OPEN_OPEN": 1,
                "OPEN_CLOSED": 2,
                "CLOSED_OPEN": 3,
                "CLOSED_CLOSED": 4
              }
            }
          }
        },
        "DiscreteDomain": {
          "fields": {
            "values": {
              "rule": "repeated",
              "type": "DomainValue",
              "id": 1
            },
            "ordered": {
              "type": "bool",
              "id": 2
            }
          }
        },
        "DomainValue": {
          "fields": {
            "value": {
              "type": "Scalar",
              "id": 1
            },
            "original_value": {
              "type": "Scalar",
              "id": 2
            },
            "display_name": {
              "type": "string",
              "id": 3
            },
            "property": {
              "type": "ValueProperty",
              "id": 4
            }
          },
          "nested": {
            "ValueProperty": {
              "values": {
                "VALID": 0,
                "INVALID": 1,
                "MISSING": 2
              }
            }
          }
        },
        "TensorType": {
          "fields": {
            "dtype": {
              "type": "DataType",
              "id": 1
            },
            "shape": {
              "rule": "repeated",
              "type": "int64",
              "id": 2
            }
          }
        },
        "Float32List": {
          "fields": {
            "values": {
              "rule": "repeated",
              "type": "float",
              "id": 1
            }
          }
        },
        "Float64List": {
          "fields": {
            "values": {
              "rule": "repeated",
              "type": "double",
              "id": 1
            }
          }
        },
        "Int32List": {
          "fields": {
            "values": {
              "rule": "repeated",
              "type": "int32",
              "id": 1
            }
          }
        },
        "Int64List": {
          "fields": {
            "values": {
              "rule": "repeated",
              "type": "int64",
              "id": 1
            }
          }
        },
        "StringList": {
          "fields": {
            "values": {
              "rule": "repeated",
              "type": "string",
              "id": 1
            }
          }
        },
        "BoolList": {
          "fields": {
            "values": {
              "rule": "repeated",
              "type": "bool",
              "id": 1
            }
          }
        },
        "BytesList": {
          "fields": {
            "values": {
              "rule": "repeated",
              "type": "bytes",
              "id": 1
            }
          }
        },
        "Tensor": {
          "oneofs": {
            "data": {
              "oneof": [
                "raw_data",
                "float32_data",
                "float64_data",
                "int32_data",
                "int64_data",
                "string_data",
                "bytes_data",
                "bool_data"
              ]
            }
          },
          "fields": {
            "name": {
              "type": "string",
              "id": 1
            },
            "type": {
              "type": "TensorType",
              "id": 2
            },
            "raw_data": {
              "type": "bytes",
              "id": 3
            },
            "float32_data": {
              "type": "Float32List",
              "id": 4
            },
            "float64_data": {
              "type": "Float64List",
              "id": 5
            },
            "int32_data": {
              "type": "Int32List",
              "id": 6
            },
            "int64_data": {
              "type": "Int64List",
              "id": 7
            },
            "string_data": {
              "type": "StringList",
              "id": 8
            },
            "bytes_data": {
              "type": "BytesList",
              "id": 9
            },
            "bool_data": {
              "type": "BoolList",
              "id": 10
            }
          }
        },
        "SparseTensor": {
          "fields": {
            "name": {
              "type": "string",
              "id": 1
            },
            "type": {
              "type": "TensorType",
              "id": 2
            },
            "default_value": {
              "type": "Scalar",
              "id": 3
            },
            "csr": {
              "type": "CSRMatrix",
              "id": 10
            }
          }
        },
        "CSRMatrix": {
          "oneofs": {
            "data": {
              "oneof": [
                "raw_data",
                "float32_data",
                "float64_data",
                "int32_data",
                "int64_data",
                "string_data"
              ]
            }
          },
          "fields": {
            "indices": {
              "rule": "repeated",
              "type": "int64",
              "id": 1
            },
            "indptr": {
              "rule": "repeated",
              "type": "int64",
              "id": 2
            },
            "raw_data": {
              "type": "bytes",
              "id": 3
            },
            "float32_data": {
              "type": "Float32List",
              "id": 4
            },
            "float64_data": {
              "type": "Float64List",
              "id": 5
            },
            "int32_data": {
              "type": "Int32List",
              "id": 6
            },
            "int64_data": {
              "type": "Int64List",
              "id": 7
            },
            "string_data": {
              "type": "StringList",
              "id": 8
            }
          }
        },
        "TensorEntry": {
          "oneofs": {
            "value": {
              "oneof": [
                "dense",
                "sparse"
              ]
            }
          },
          "fields": {
            "id": {
              "type": "string",
              "id": 1
            },
            "dense": {
              "type": "Tensor",
              "id": 2
            },
            "sparse": {
              "type": "SparseTensor",
              "id": 3
            },
            "attributes": {
              "keyType": "string",
              "type": "string",
              "id": 20
            }
          }
        },
        "TensorRef": {
          "fields": {
            "id": {
              "type": "string",
              "id": 1
            }
          }
        },
        "TensorValue": {
          "oneofs": {
            "value": {
              "oneof": [
                "tensor",
                "sparse",
                "tensor_ref"
              ]
            }
          },
          "fields": {
            "tensor": {
              "type": "Tensor",
              "id": 1
            },
            "sparse": {
              "type": "SparseTensor",
              "id": 2
            },
            "tensor_ref": {
              "type": "TensorRef",
              "id": 3
            }
          }
        },
        "NameRef": {
          "fields": {
            "value": {
              "type": "string",
              "id": 1
            },
            "field": {
              "type": "string",
              "id": 2
            }
          }
        },
        "Expression": {
          "oneofs": {
            "kind": {
              "oneof": [
                "literal",
                "ref",
                "apply"
              ]
            }
          },
          "fields": {
            "literal": {
              "type": "Scalar",
              "id": 1
            },
            "ref": {
              "type": "NameRef",
              "id": 2
            },
            "apply": {
              "type": "Apply",
              "id": 3
            }
          }
        },
        "Apply": {
          "fields": {
            "function": {
              "type": "string",
              "id": 1
            },
            "arguments": {
              "rule": "repeated",
              "type": "Expression",
              "id": 2
            }
          }
        },
        "Predicate": {
          "oneofs": {
            "kind": {
              "oneof": [
                "true_predicate",
                "false_predicate",
                "simple",
                "simple_set",
                "compound"
              ]
            }
          },
          "fields": {
            "true_predicate": {
              "type": "TruePredicate",
              "id": 1
            },
            "false_predicate": {
              "type": "FalsePredicate",
              "id": 2
            },
            "simple": {
              "type": "SimplePredicate",
              "id": 3
            },
            "simple_set": {
              "type": "SimpleSetPredicate",
              "id": 4
            },
            "compound": {
              "type": "CompoundPredicate",
              "id": 5
            }
          }
        },
        "TruePredicate": {
          "fields": {}
        },
        "FalsePredicate": {
          "fields": {}
        },
        "SimplePredicate": {
          "fields": {
            "column": {
              "type": "NameRef",
              "id": 1
            },
            "op": {
              "type": "Operator",
              "id": 2
            },
            "value": {
              "type": "Scalar",
              "id": 3
            }
          },
          "nested": {
            "Operator": {
              "values": {
                "OPERATOR_UNSPECIFIED": 0,
                "LESS_THAN": 1,
                "LESS_OR_EQUAL": 2,
                "GREATER_THAN": 3,
                "GREATER_OR_EQUAL": 4,
                "EQUAL": 5,
                "NOT_EQUAL": 6,
                "IS_MISSING": 7,
                "IS_NOT_MISSING": 8
              }
            }
          }
        },
        "SimpleSetPredicate": {
          "fields": {
            "column": {
              "type": "NameRef",
              "id": 1
            },
            "op": {
              "type": "Operator",
              "id": 2
            },
            "values": {
              "rule": "repeated",
              "type": "Scalar",
              "id": 3
            }
          },
          "nested": {
            "Operator": {
              "values": {
                "OPERATOR_UNSPECIFIED": 0,
                "IN": 1,
                "NOT_IN": 2
              }
            }
          }
        },
        "CompoundPredicate": {
          "fields": {
            "op": {
              "type": "BooleanOperator",
              "id": 1
            },
            "predicates": {
              "rule": "repeated",
              "type": "Predicate",
              "id": 2
            }
          },
          "nested": {
            "BooleanOperator": {
              "values": {
                "BOOLEAN_OPERATOR_UNSPECIFIED": 0,
                "AND": 1,
                "OR": 2,
                "XOR": 3,
                "SURROGATE": 4
              }
            }
          }
        },
        "DefineFunction": {
          "fields": {
            "name": {
              "type": "string",
              "id": 1
            },
            "doc_string": {
              "type": "string",
              "id": 2
            },
            "parameters": {
              "rule": "repeated",
              "type": "Parameter",
              "id": 3
            },
            "result_data_type": {
              "type": "DataType",
              "id": 4
            },
            "result_measure_level": {
              "type": "MeasureLevel",
              "id": 5
            },
            "body": {
              "type": "Expression",
              "id": 6
            },
            "attributes": {
              "keyType": "string",
              "type": "string",
              "id": 20
            }
          },
          "nested": {
            "Parameter": {
              "fields": {
                "name": {
                  "type": "string",
                  "id": 1
                },
                "data_type": {
                  "type": "DataType",
                  "id": 2
                },
                "measure_level": {
                  "type": "MeasureLevel",
                  "id": 3
                }
              }
            }
          }
        },
        "NodeInput": {
          "oneofs": {
            "ref": {
              "oneof": [
                "name",
                "range"
              ]
            }
          },
          "fields": {
            "name": {
              "type": "NameRef",
              "id": 1
            },
            "range": {
              "type": "NameRange",
              "id": 2
            }
          }
        },
        "NodeOutput": {
          "fields": {
            "name": {
              "type": "string",
              "id": 1
            },
            "type": {
              "type": "TensorType",
              "id": 2
            },
            "measure_level": {
              "type": "MeasureLevel",
              "id": 3
            },
            "domain": {
              "type": "ValueDomain",
              "id": 4
            },
            "description": {
              "type": "string",
              "id": 5
            },
            "role": {
              "type": "OutputRole",
              "id": 6
            },
            "binding": {
              "type": "OutputBinding",
              "id": 7
            },
            "field_names": {
              "rule": "repeated",
              "type": "string",
              "id": 8
            },
            "attributes": {
              "keyType": "string",
              "type": "string",
              "id": 20
            }
          }
        },
        "NameAlias": {
          "fields": {
            "from_name": {
              "type": "string",
              "id": 1
            },
            "to_name": {
              "type": "string",
              "id": 2
            }
          }
        },
        "CompositeNode": {
          "fields": {
            "input_aliases": {
              "rule": "repeated",
              "type": "NameAlias",
              "id": 1
            },
            "nodes": {
              "rule": "repeated",
              "type": "Node",
              "id": 2
            },
            "output_aliases": {
              "rule": "repeated",
              "type": "NameAlias",
              "id": 3
            }
          }
        },
        "Node": {
          "oneofs": {
            "body": {
              "oneof": [
                "composite",
                "tree",
                "tree_ensemble",
                "linear",
                "naive_bayes",
                "clustering",
                "svm",
                "neural_network",
                "anomaly_detection"
              ]
            }
          },
          "fields": {
            "name": {
              "type": "string",
              "id": 1
            },
            "domain": {
              "type": "string",
              "id": 2
            },
            "op": {
              "type": "string",
              "id": 3
            },
            "inputs": {
              "rule": "repeated",
              "type": "NodeInput",
              "id": 4
            },
            "outputs": {
              "rule": "repeated",
              "type": "NodeOutput",
              "id": 5
            },
            "attributes": {
              "rule": "repeated",
              "type": "Attribute",
              "id": 6
            },
            "composite": {
              "type": "CompositeNode",
              "id": 20
            },
            "tree": {
              "type": "Tree",
              "id": 30
            },
            "tree_ensemble": {
              "type": "TreeEnsemble",
              "id": 31
            },
            "linear": {
              "type": "Linear",
              "id": 32
            },
            "naive_bayes": {
              "type": "NaiveBayes",
              "id": 33
            },
            "clustering": {
              "type": "Clustering",
              "id": 34
            },
            "svm": {
              "type": "SVM",
              "id": 35
            },
            "neural_network": {
              "type": "NeuralNetwork",
              "id": 36
            },
            "anomaly_detection": {
              "type": "AnomalyDetection",
              "id": 37
            },
            "metadata": {
              "keyType": "string",
              "type": "string",
              "id": 100
            }
          }
        },
        "Attribute": {
          "oneofs": {
            "value": {
              "oneof": [
                "i",
                "f32",
                "f64",
                "s",
                "b",
                "ints",
                "float32s",
                "float64s",
                "strings",
                "bools",
                "tensor_ref",
                "tensor",
                "sparse",
                "type",
                "expr",
                "predicate"
              ]
            }
          },
          "fields": {
            "name": {
              "type": "string",
              "id": 1
            },
            "i": {
              "type": "int64",
              "id": 2
            },
            "f32": {
              "type": "float",
              "id": 3
            },
            "f64": {
              "type": "double",
              "id": 4
            },
            "s": {
              "type": "string",
              "id": 5
            },
            "b": {
              "type": "bool",
              "id": 6
            },
            "ints": {
              "type": "Int64List",
              "id": 7
            },
            "float32s": {
              "type": "Float32List",
              "id": 8
            },
            "float64s": {
              "type": "Float64List",
              "id": 9
            },
            "strings": {
              "type": "StringList",
              "id": 10
            },
            "bools": {
              "type": "BoolList",
              "id": 11
            },
            "tensor_ref": {
              "type": "TensorRef",
              "id": 12
            },
            "tensor": {
              "type": "Tensor",
              "id": 13
            },
            "sparse": {
              "type": "SparseTensor",
              "id": 14
            },
            "type": {
              "type": "TensorType",
              "id": 15
            },
            "expr": {
              "type": "Expression",
              "id": 16
            },
            "predicate": {
              "type": "Predicate",
              "id": 17
            }
          }
        },
        "PostTransform": {
          "values": {
            "POST_TRANSFORM_UNSPECIFIED": 0,
            "IDENTITY": 1,
            "SIGMOID": 2,
            "SIGMOID_BINARY": 3,
            "SOFTMAX": 4,
            "LOGIT": 5,
            "PROBIT": 6,
            "EXP": 7,
            "CLOGLOG": 8,
            "CAUCHIT": 9,
            "LOGLOG": 10
          }
        },
        "Tree": {
          "fields": {
            "task_type": {
              "type": "TaskType",
              "id": 1
            },
            "num_nodes": {
              "type": "int32",
              "id": 2
            },
            "node_kind": {
              "rule": "repeated",
              "type": "NodeKind",
              "id": 3
            },
            "split_feature": {
              "rule": "repeated",
              "type": "int32",
              "id": 10
            },
            "split_threshold": {
              "type": "TensorValue",
              "id": 11
            },
            "split_op": {
              "rule": "repeated",
              "type": "SplitOp",
              "id": 12
            },
            "category_set_offset": {
              "rule": "repeated",
              "type": "int32",
              "id": 20
            },
            "category_set_count": {
              "rule": "repeated",
              "type": "int32",
              "id": 21
            },
            "category_set": {
              "rule": "repeated",
              "type": "int32",
              "id": 22
            },
            "complex_predicates": {
              "rule": "repeated",
              "type": "ComplexPredicate",
              "id": 23
            },
            "children_index": {
              "rule": "repeated",
              "type": "int32",
              "id": 30
            },
            "children_offset": {
              "rule": "repeated",
              "type": "int32",
              "id": 31
            },
            "children_count": {
              "rule": "repeated",
              "type": "int32",
              "id": 32
            },
            "default_child": {
              "rule": "repeated",
              "type": "int32",
              "id": 33
            },
            "leaf_value": {
              "type": "TensorValue",
              "id": 40
            },
            "leaf_width": {
              "type": "int32",
              "id": 41
            },
            "leaf_vector": {
              "type": "TensorValue",
              "id": 42
            },
            "leaf_vector_index": {
              "rule": "repeated",
              "type": "int32",
              "id": 43
            }
          },
          "nested": {
            "NodeKind": {
              "values": {
                "NODE_KIND_UNSPECIFIED": 0,
                "LEAF": 1,
                "BRANCH": 2
              }
            },
            "SplitOp": {
              "values": {
                "SPLIT_OP_UNSPECIFIED": 0,
                "LESS_THAN": 1,
                "LESS_OR_EQUAL": 2,
                "GREATER_THAN": 3,
                "GREATER_OR_EQUAL": 4,
                "EQUAL": 5,
                "NOT_EQUAL": 6,
                "IN_SET": 7,
                "NOT_IN_SET": 8,
                "IS_MISSING": 9
              }
            },
            "ComplexPredicate": {
              "fields": {
                "node_index": {
                  "type": "int32",
                  "id": 1
                },
                "predicate": {
                  "type": "Predicate",
                  "id": 2
                }
              }
            }
          }
        },
        "TreeEnsemble": {
          "oneofs": {
            "_tree_weights": {
              "oneof": [
                "tree_weights"
              ]
            },
            "_base_scores": {
              "oneof": [
                "base_scores"
              ]
            }
          },
          "fields": {
            "task_type": {
              "type": "TaskType",
              "id": 1
            },
            "trees": {
              "rule": "repeated",
              "type": "Tree",
              "id": 2
            },
            "aggregation": {
              "type": "Aggregation",
              "id": 3
            },
            "tree_weights": {
              "type": "TensorValue",
              "id": 4,
              "options": {
                "proto3_optional": true
              }
            },
            "base_scores": {
              "type": "TensorValue",
              "id": 5,
              "options": {
                "proto3_optional": true
              }
            },
            "tree_group": {
              "rule": "repeated",
              "type": "int32",
              "id": 6
            },
            "post_transform": {
              "type": "PostTransform",
              "id": 10
            }
          },
          "nested": {
            "Aggregation": {
              "values": {
                "AGGREGATION_UNSPECIFIED": 0,
                "SUM": 1,
                "AVERAGE": 2,
                "WEIGHTED_SUM": 3,
                "WEIGHTED_AVERAGE": 4,
                "MAJORITY_VOTE": 5,
                "SOFT_VOTE": 6,
                "MIN": 7,
                "MAX": 8
              }
            }
          }
        },
        "Linear": {
          "oneofs": {
            "_intercept": {
              "oneof": [
                "intercept"
              ]
            },
            "_weight_covariances": {
              "oneof": [
                "weight_covariances"
              ]
            },
            "_noise_precision": {
              "oneof": [
                "noise_precision"
              ]
            }
          },
          "fields": {
            "task_type": {
              "type": "TaskType",
              "id": 1
            },
            "coefficients": {
              "type": "TensorValue",
              "id": 2
            },
            "intercept": {
              "type": "TensorValue",
              "id": 3,
              "options": {
                "proto3_optional": true
              }
            },
            "weight_covariances": {
              "type": "TensorValue",
              "id": 4,
              "options": {
                "proto3_optional": true
              }
            },
            "noise_precision": {
              "type": "TensorValue",
              "id": 5,
              "options": {
                "proto3_optional": true
              }
            },
            "post_transform": {
              "type": "PostTransform",
              "id": 10
            }
          }
        },
        "NaiveBayes": {
          "oneofs": {
            "implementation": {
              "oneof": [
                "gaussian",
                "multinomial",
                "bernoulli",
                "categorical"
              ]
            }
          },
          "fields": {
            "task_type": {
              "type": "TaskType",
              "id": 1
            },
            "class_log_priors": {
              "type": "TensorValue",
              "id": 2
            },
            "gaussian": {
              "type": "GaussianNaiveBayes",
              "id": 10
            },
            "multinomial": {
              "type": "MultinomialNaiveBayes",
              "id": 11
            },
            "bernoulli": {
              "type": "BernoulliNaiveBayes",
              "id": 12
            },
            "categorical": {
              "type": "CategoricalNaiveBayes",
              "id": 13
            }
          }
        },
        "GaussianNaiveBayes": {
          "oneofs": {
            "_variance_epsilon": {
              "oneof": [
                "variance_epsilon"
              ]
            }
          },
          "fields": {
            "means": {
              "type": "TensorValue",
              "id": 1
            },
            "variances": {
              "type": "TensorValue",
              "id": 2
            },
            "variance_epsilon": {
              "type": "Scalar",
              "id": 3,
              "options": {
                "proto3_optional": true
              }
            }
          }
        },
        "MultinomialNaiveBayes": {
          "fields": {
            "feature_log_prob": {
              "type": "TensorValue",
              "id": 1
            }
          }
        },
        "BernoulliNaiveBayes": {
          "oneofs": {
            "_binarize_threshold": {
              "oneof": [
                "binarize_threshold"
              ]
            }
          },
          "fields": {
            "feature_log_prob": {
              "type": "TensorValue",
              "id": 1
            },
            "binarize_threshold": {
              "type": "Scalar",
              "id": 2,
              "options": {
                "proto3_optional": true
              }
            }
          }
        },
        "CategoricalNaiveBayes": {
          "fields": {
            "category_log_prob": {
              "type": "TensorValue",
              "id": 1
            },
            "category_offset": {
              "rule": "repeated",
              "type": "int32",
              "id": 2
            },
            "category_count": {
              "rule": "repeated",
              "type": "int32",
              "id": 3
            }
          }
        },
        "Clustering": {
          "oneofs": {
            "implementation": {
              "oneof": [
                "prototype",
                "gaussian_mixture"
              ]
            }
          },
          "fields": {
            "task_type": {
              "type": "TaskType",
              "id": 1
            },
            "prototype": {
              "type": "PrototypeClustering",
              "id": 10
            },
            "gaussian_mixture": {
              "type": "GaussianMixtureClustering",
              "id": 11
            }
          }
        },
        "PrototypeClustering": {
          "fields": {
            "centers": {
              "type": "TensorValue",
              "id": 1
            },
            "distance_measure": {
              "type": "DistanceMeasure",
              "id": 2
            },
            "cluster_labels": {
              "rule": "repeated",
              "type": "Scalar",
              "id": 3
            }
          },
          "nested": {
            "DistanceMeasure": {
              "values": {
                "DISTANCE_MEASURE_UNSPECIFIED": 0,
                "EUCLIDEAN": 1,
                "SQUARED_EUCLIDEAN": 2,
                "MANHATTAN": 3,
                "COSINE": 4
              }
            }
          }
        },
        "GaussianMixtureClustering": {
          "fields": {
            "weights": {
              "type": "TensorValue",
              "id": 1
            },
            "means": {
              "type": "TensorValue",
              "id": 2
            },
            "covariances": {
              "type": "TensorValue",
              "id": 3
            },
            "covariance_type": {
              "type": "CovarianceType",
              "id": 4
            },
            "component_labels": {
              "rule": "repeated",
              "type": "Scalar",
              "id": 5
            }
          },
          "nested": {
            "CovarianceType": {
              "values": {
                "COVARIANCE_TYPE_UNSPECIFIED": 0,
                "FULL": 1,
                "DIAGONAL": 2,
                "SPHERICAL": 3
              }
            }
          }
        },
        "SVM": {
          "oneofs": {
            "_multiclass_strategy": {
              "oneof": [
                "multiclass_strategy"
              ]
            },
            "implementation": {
              "oneof": [
                "linear",
                "kernel"
              ]
            }
          },
          "fields": {
            "task_type": {
              "type": "TaskType",
              "id": 1
            },
            "multiclass_strategy": {
              "type": "MulticlassStrategy",
              "id": 3,
              "options": {
                "proto3_optional": true
              }
            },
            "linear": {
              "type": "LinearSVM",
              "id": 10
            },
            "kernel": {
              "type": "KernelSVM",
              "id": 11
            },
            "post_transform": {
              "type": "PostTransform",
              "id": 20
            }
          },
          "nested": {
            "MulticlassStrategy": {
              "values": {
                "MULTICLASS_STRATEGY_UNSPECIFIED": 0,
                "ONE_VS_REST": 1,
                "ONE_VS_ONE": 2
              }
            }
          }
        },
        "LinearSVM": {
          "oneofs": {
            "_intercept": {
              "oneof": [
                "intercept"
              ]
            }
          },
          "fields": {
            "coefficients": {
              "type": "TensorValue",
              "id": 1
            },
            "intercept": {
              "type": "TensorValue",
              "id": 2,
              "options": {
                "proto3_optional": true
              }
            }
          }
        },
        "KernelSVM": {
          "oneofs": {
            "_intercept": {
              "oneof": [
                "intercept"
              ]
            },
            "_gamma": {
              "oneof": [
                "gamma"
              ]
            },
            "_degree": {
              "oneof": [
                "degree"
              ]
            },
            "_coef0": {
              "oneof": [
                "coef0"
              ]
            },
            "_prob_a": {
              "oneof": [
                "prob_a"
              ]
            },
            "_prob_b": {
              "oneof": [
                "prob_b"
              ]
            }
          },
          "fields": {
            "kernel_type": {
              "type": "KernelType",
              "id": 1
            },
            "support_vectors": {
              "type": "TensorValue",
              "id": 2
            },
            "dual_coefficients": {
              "type": "TensorValue",
              "id": 3
            },
            "intercept": {
              "type": "TensorValue",
              "id": 4,
              "options": {
                "proto3_optional": true
              }
            },
            "gamma": {
              "type": "Scalar",
              "id": 5,
              "options": {
                "proto3_optional": true
              }
            },
            "degree": {
              "type": "int32",
              "id": 6,
              "options": {
                "proto3_optional": true
              }
            },
            "coef0": {
              "type": "Scalar",
              "id": 7,
              "options": {
                "proto3_optional": true
              }
            },
            "n_support": {
              "rule": "repeated",
              "type": "int64",
              "id": 8
            },
            "prob_a": {
              "type": "TensorValue",
              "id": 9,
              "options": {
                "proto3_optional": true
              }
            },
            "prob_b": {
              "type": "TensorValue",
              "id": 10,
              "options": {
                "proto3_optional": true
              }
            }
          },
          "nested": {
            "KernelType": {
              "values": {
                "KERNEL_TYPE_UNSPECIFIED": 0,
                "LINEAR": 1,
                "POLY": 2,
                "RBF": 3,
                "SIGMOID": 4
              }
            }
          }
        },
        "NeuralNetwork": {
          "fields": {
            "task_type": {
              "type": "TaskType",
              "id": 1
            },
            "layers": {
              "rule": "repeated",
              "type": "DenseLayer",
              "id": 2
            }
          },
          "nested": {
            "Activation": {
              "values": {
                "ACTIVATION_UNSPECIFIED": 0,
                "IDENTITY": 1,
                "LOGISTIC": 2,
                "TANH": 3,
                "RELU": 4,
                "SOFTMAX": 5
              }
            },
            "DenseLayer": {
              "oneofs": {
                "_bias": {
                  "oneof": [
                    "bias"
                  ]
                }
              },
              "fields": {
                "weights": {
                  "type": "TensorValue",
                  "id": 1
                },
                "bias": {
                  "type": "TensorValue",
                  "id": 2,
                  "options": {
                    "proto3_optional": true
                  }
                },
                "activation": {
                  "type": "Activation",
                  "id": 3
                },
                "name": {
                  "type": "string",
                  "id": 4
                }
              }
            }
          }
        },
        "AnomalyDetection": {
          "oneofs": {
            "_threshold": {
              "oneof": [
                "threshold"
              ]
            },
            "implementation": {
              "oneof": [
                "isolation_forest",
                "one_class_svm",
                "linear_one_class_svm",
                "local_outlier_factor",
                "elliptic_envelope"
              ]
            }
          },
          "fields": {
            "task_type": {
              "type": "TaskType",
              "id": 1
            },
            "mode": {
              "type": "DetectionMode",
              "id": 2
            },
            "raw_score_polarity": {
              "type": "ScorePolarity",
              "id": 3
            },
            "threshold": {
              "type": "Scalar",
              "id": 4,
              "options": {
                "proto3_optional": true
              }
            },
            "isolation_forest": {
              "type": "IsolationForest",
              "id": 10
            },
            "one_class_svm": {
              "type": "OneClassSVM",
              "id": 11
            },
            "linear_one_class_svm": {
              "type": "LinearOneClassSVM",
              "id": 12
            },
            "local_outlier_factor": {
              "type": "LocalOutlierFactor",
              "id": 13
            },
            "elliptic_envelope": {
              "type": "EllipticEnvelope",
              "id": 14
            }
          },
          "nested": {
            "DetectionMode": {
              "values": {
                "DETECTION_MODE_UNSPECIFIED": 0,
                "OUTLIER_DETECTION": 1,
                "NOVELTY_DETECTION": 2
              }
            },
            "ScorePolarity": {
              "values": {
                "SCORE_POLARITY_UNSPECIFIED": 0,
                "HIGHER_MORE_ABNORMAL": 1,
                "LOWER_MORE_ABNORMAL": 2
              }
            }
          }
        },
        "IsolationForest": {
          "oneofs": {
            "_offset": {
              "oneof": [
                "offset"
              ]
            }
          },
          "fields": {
            "trees": {
              "rule": "repeated",
              "type": "Tree",
              "id": 1
            },
            "max_samples": {
              "type": "int64",
              "id": 2
            },
            "offset": {
              "type": "Scalar",
              "id": 3,
              "options": {
                "proto3_optional": true
              }
            }
          }
        },
        "OneClassSVM": {
          "oneofs": {
            "_offset": {
              "oneof": [
                "offset"
              ]
            }
          },
          "fields": {
            "kernel_svm": {
              "type": "KernelSVM",
              "id": 1
            },
            "offset": {
              "type": "Scalar",
              "id": 2,
              "options": {
                "proto3_optional": true
              }
            }
          }
        },
        "LinearOneClassSVM": {
          "oneofs": {
            "_intercept": {
              "oneof": [
                "intercept"
              ]
            },
            "_offset": {
              "oneof": [
                "offset"
              ]
            }
          },
          "fields": {
            "coefficients": {
              "type": "TensorValue",
              "id": 1
            },
            "intercept": {
              "type": "TensorValue",
              "id": 2,
              "options": {
                "proto3_optional": true
              }
            },
            "offset": {
              "type": "Scalar",
              "id": 3,
              "options": {
                "proto3_optional": true
              }
            }
          }
        },
        "LocalOutlierFactor": {
          "oneofs": {
            "_offset": {
              "oneof": [
                "offset"
              ]
            }
          },
          "fields": {
            "reference_samples": {
              "type": "TensorValue",
              "id": 1
            },
            "n_neighbors": {
              "type": "int32",
              "id": 2
            },
            "metric": {
              "type": "string",
              "id": 3
            },
            "metric_params": {
              "keyType": "string",
              "type": "string",
              "id": 4
            },
            "offset": {
              "type": "Scalar",
              "id": 5,
              "options": {
                "proto3_optional": true
              }
            }
          }
        },
        "EllipticEnvelope": {
          "oneofs": {
            "_precision": {
              "oneof": [
                "precision"
              ]
            },
            "_offset": {
              "oneof": [
                "offset"
              ]
            }
          },
          "fields": {
            "location": {
              "type": "TensorValue",
              "id": 1
            },
            "covariance": {
              "type": "TensorValue",
              "id": 2
            },
            "precision": {
              "type": "TensorValue",
              "id": 3,
              "options": {
                "proto3_optional": true
              }
            },
            "offset": {
              "type": "Scalar",
              "id": 4,
              "options": {
                "proto3_optional": true
              }
            }
          }
        },
        "NumericTolerance": {
          "oneofs": {
            "_atol": {
              "oneof": [
                "atol"
              ]
            },
            "_rtol": {
              "oneof": [
                "rtol"
              ]
            }
          },
          "fields": {
            "atol": {
              "type": "Scalar",
              "id": 1,
              "options": {
                "proto3_optional": true
              }
            },
            "rtol": {
              "type": "Scalar",
              "id": 2,
              "options": {
                "proto3_optional": true
              }
            }
          }
        },
        "ModelVerification": {
          "fields": {
            "cases": {
              "rule": "repeated",
              "type": "VerificationCase",
              "id": 1
            },
            "tolerance": {
              "type": "NumericTolerance",
              "id": 2
            }
          }
        },
        "VerificationCase": {
          "fields": {
            "inputs": {
              "rule": "repeated",
              "type": "TensorRef",
              "id": 1
            },
            "expected_outputs": {
              "rule": "repeated",
              "type": "TensorRef",
              "id": 2
            },
            "description": {
              "type": "string",
              "id": 3
            }
          }
        },
        "RuntimeWarmup": {
          "fields": {
            "cases": {
              "rule": "repeated",
              "type": "WarmupCase",
              "id": 1
            }
          }
        },
        "WarmupCase": {
          "fields": {
            "inputs": {
              "rule": "repeated",
              "type": "TensorRef",
              "id": 1
            },
            "description": {
              "type": "string",
              "id": 2
            },
            "repeat": {
              "type": "int32",
              "id": 3
            }
          }
        },
        "SampleInputSet": {
          "fields": {
            "cases": {
              "rule": "repeated",
              "type": "SampleInputCase",
              "id": 1
            }
          }
        },
        "SampleInputCase": {
          "fields": {
            "inputs": {
              "rule": "repeated",
              "type": "TensorRef",
              "id": 1
            },
            "description": {
              "type": "string",
              "id": 2
            }
          }
        }
      }
    }
  }
} as unknown as INamespace;

export default protoDescriptor;
